import { getFromToPlace } from "./Table/Icons";

export const column = [
	{
		key:"title",
		name:"Title",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"INPUT",
		resizable:false
	},
	{
		key:"area",
		name:"Area",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"INPUT",
		resizable:true
		
	},
	{
		key:"id",
		name:"Id",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"Date",
		resizable:true
	},
	{
		key:"available",
		name:"Available",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"SELECT",
		resizable:true,
		selectOptions:[{ value: 1, label: 'Yes' }, { value: 1, label: 'Yes' }],
		loadOptions:getFromToPlace
	},
	{
		key:"version",
		name:"Version",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"INPUT",
		resizable:true
	},
	{
		key:"AQS",
		name:"Version",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"INPUT",
		resizable:true
	},
	{
		key:"AQ234",
		name:"Version",
		width:180,
		cellClass:"",
		editable:true,
		cellType:"INPUT",
		resizable:true
	}
]