import HeaderCell from "./Cells/HeaderCell";

export const column = [
	{
		key:"title",
		name:"title",
		width:180,
		cellClass:"",
		editable:"true",
		cellType:"Input",
		headerRender:HeaderCell,
		resizable:true
	},
	{
		key:"area",
		name:"area",
		width:180,
		cellClass:"",
		editable:"true",
		cellType:"Input",
		headerRender:HeaderCell,
		resizable:true
		
	},
	{
		key:"id",
		name:"id",
		width:180,
		cellClass:"",
		editable:"true",
		cellType:"Input",
		headerRender:HeaderCell,
		resizable:true
	},
	{
		key:"available",
		name:"available",
		width:180,
		cellClass:"",
		editable:"true",
		cellType:"Input",
		headerRender:HeaderCell,
		resizable:true
	},
	{
		key:"version",
		name:"version",
		width:180,
		cellClass:"",
		editable:"true",
		cellType:"Input",
		headerRender:HeaderCell,
		resizable:true
	}
]